name: TS & Svelte Check

on:
  - push

jobs:
  check:
    runs-on: ubuntu-latest
    env:
      PUBLIC_BETTER_AUTH_URL: http://localhost:3000
    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - uses: pnpm/action-setup@v3
        name: Install pnpm
        with:
          version: 8
          run_install: true

      - run: pnpm check
